### PR TITLE
multithreading support

### PR DESCRIPTION
**Pull request by jeff-regier**

### CODE REVIEW

**Comment by jeff-regier** [comment]
Without the lock around the call to `wcss2p`, I get the following error:

```
*** Error in `/global/homes/j/jregier/julia/bin/julia-debug': double free or corruption (fasttop): 0x00002
aacbc0a16a0 ***
*** Error in `/global/homes/j/jregier/julia/bin/julia-debug': malloc(): memory corruption (fast): 0x00002a
ac00000010 ***
fatal flex scanner internal error--no action found

signal (11): Segmentation fault

signal (11): Segmentation fault
while loading /global/homes/j/jregier/.julia/v0.5/Celeste/bin/celeste.jl, in expression starting on line 8
2
while loading /global/homes/j/jregier/.julia/v0.5/Celeste/bin/celeste.jl, in expression starting on line 8
2
*** Error in `/global/homes/j/jregier/julia/bin/julia-debug': malloc(): memory corruption: 0x00002aacc4bd0
800 ***
yy_get_previ/global/u2/j//global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.137187
yy_get_previ/global/u2/j//global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.137187
wcsulexe at /global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.13/C/wcsulex.c:8435
wcsunitse at /global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.13/C/wcsunits.c:117
wcsunitse at /global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.13/C/wcsunits.c:117
unknown function (ip: 0x2aacfcf809d0)
wcs_units at /global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.13/C/wcs.c:2580 [inlined]
wcsset at /global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.13/C/wcs.c:1923
wcss2p at /global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.13/C/wcs.c:2871
*** Error in `/global/homes/j/jregier/julia/bin/julia-debug': double free or corruption (fasttop): 0x00000
00003e3ce40 ***
*** Error in `/global/homes/j/jregier/julia/bin/julia-debug': double free or corruption (fasttop): 0x00002
aacb8b7b7c0 ***
wcss2p at /global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.13/C/wcs.c:2871
fatal flex scanner internal error--end of buffer missed
#world_to_pix!#4 at /global/homes/j/jregier/.julia/v0.5/WCS/src/WCS.jl:603
#world_to_pix!#4 at /global/homes/j/jregier/.julia/v0.5/WCS/src/WCS.jl:603

signal (11): Segmentation fault
while loading /global/homes/j/jregier/.julia/v0.5/Celeste/bin/celeste.jl, in expression starting on line 8
2
fatal flex scanner internal error--end of buffer missed
fatal flex scanner internal error--end of buffer missed
```

**Comment by kbarbary** [comment]
I added this line to the `WCSTransform` constructor (right before the return) and was able to run `pix_to_world` without a segfault:

```julia
        # wcsset is not threadsafe, so call it here so it doesn't get called
        # in wcss2p and wcsp2s.
        status = ccall((:wcsset, libwcs), Cint, (Ref{WCSTransform},), w)
```

Of course, the constructor itself should then have locks around it.

**Comment by jeff-regier** [comment]
Still seeing

```
signal (6): Aborted
while loading /global/homes/j/jregier/.julia/v0.5/Celeste/bin/celeste.jl, in expression starting on line 82
wcsulex_delete_buffer at /global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.13/C/wcsulex.c:8936
wcsulexlex_destroy at /global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.13/C/wcsulex.c:9321
wcsulexe at /global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.13/C/wcsulex.l:939
wcsunitse at /global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.13/C/wcsunits.c:117
wcs_units at /global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.13/C/wcs.c:2580 [inlined]
wcsset at /global/u2/j/jregier/WCS.jl/deps/src/wcslib-5.13/C/wcs.c:1923
fatal flex scanner internal error--end of buffer missed
```

**Comment by kbarbary** [comment]
Closing in favor of #8.

**Pull request closed without merging**
